  CREATE TABLE "ADMIN" 
   (	"USER_ID" NUMBER, 
	"ADMIN_ROLE" VARCHAR2(100), 
	"PERMISSIONS" VARCHAR2(200), 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CART" 
   (	"CART_ID" NUMBER, 
	"CREATED_DATE" TIMESTAMP (6), 
	"CUSTOMER_ID" NUMBER, 
	"STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("CART_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CART_ITEM" 
   (	"CART_ITEM_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER(10,2), 
	"CART_ID" NUMBER, 
	 PRIMARY KEY ("CART_ITEM_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	 PRIMARY KEY ("CATEGORY_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "COLLECTION_SLOT" 
   (	"SLOT_ID" NUMBER, 
	"COLLECTION_DATE" DATE, 
	"COLLECTION_TIME" VARCHAR2(20), 
	"LOCATION" VARCHAR2(100), 
	 PRIMARY KEY ("SLOT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CUSTOMER" 
   (	"USER_ID" NUMBER, 
	"LOYALTY_POINTS" NUMBER, 
	"DATE_OF_BIRTH" DATE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISCOUNT" 
   (	"DISCOUNT_ID" NUMBER, 
	"DISCOUNT_NAME" VARCHAR2(100), 
	"DISCOUNT_RATE" NUMBER(5,2), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	 PRIMARY KEY ("DISCOUNT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ORDER" 
   (	"ORDER_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"SLOT_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"TOTAL_PRICE" NUMBER(10,2), 
	"STATUS" VARCHAR2(50), 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"ORDER_DATE" DATE, 
	"TOTAL_AMOUNT" NUMBER(10,2), 
	"STATUS" VARCHAR2(50), 
	"CUSTOMER_ID" NUMBER, 
	"SLOT_ID" NUMBER, 
	 PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ORDER_ITEM" 
   (	"ORDER_ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRICE" NUMBER(10,2), 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	 PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENT" 
   (	"PAYMENT_ID" NUMBER, 
	"PAYMENT_DATE" TIMESTAMP (6), 
	"AMOUNT" NUMBER(10,2), 
	"PAYMENT_STATUS" VARCHAR2(50), 
	"ORDER_ID" NUMBER, 
	"METHOD_ID" NUMBER, 
	"USER_ID" NUMBER, 
	 PRIMARY KEY ("PAYMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PAYMENT_METHOD" 
   (	"METHOD_ID" NUMBER, 
	"METHOD_NAME" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(200), 
	 PRIMARY KEY ("METHOD_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"PRICE" NUMBER(10,2), 
	"STOCK_QUANTITY" NUMBER, 
	"EXPIRY_DATE" DATE, 
	"SHOP_ID" NUMBER, 
	"CATEGORY_ID" NUMBER, 
	"QUANTITY_PER_ITEM" NUMBER, 
	"MIN_ORDER" NUMBER, 
	"MAX_ORDER" NUMBER, 
	"ALLERGY_INFO" VARCHAR2(200), 
	 PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRODUCT_DISCOUNT" 
   (	"PRODUCT_ID" NUMBER, 
	"DISCOUNT_ID" NUMBER, 
	 PRIMARY KEY ("PRODUCT_ID", "DISCOUNT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "REVIEW" 
   (	"REVIEW_ID" NUMBER, 
	"RATING" NUMBER, 
	"COMMENT_TEXT" VARCHAR2(255), 
	"REVIEW_DATE" DATE, 
	"CUSTOMER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"DISPLAY_FLAG" CHAR(1), 
	 PRIMARY KEY ("REVIEW_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SHOP" 
   (	"SHOP_ID" NUMBER, 
	"SHOP_NAME" VARCHAR2(100), 
	"LOCATION" VARCHAR2(100), 
	"CONTACT_NO" VARCHAR2(20), 
	"TRADER_ID" NUMBER, 
	 PRIMARY KEY ("SHOP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SYSTEM_USER" 
   (	"USER_ID" NUMBER, 
	"NAME" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(100), 
	"PHONE_NO" VARCHAR2(20), 
	"ADDRESS" VARCHAR2(200), 
	"CREATED_AT" DATE, 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "TRADER" 
   (	"USER_ID" NUMBER, 
	"BUSINESS_NAME" VARCHAR2(100), 
	"LICENSE_NO" VARCHAR2(50), 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_ADMIN_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM_USER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ADMIN_DEFAULT" 
BEFORE INSERT ON ADMIN
FOR EACH ROW
BEGIN
    -- Set default role
    IF :NEW.admin_role IS NULL THEN
        :NEW.admin_role := 'Manager';
    END IF;

    -- Set default permissions
    IF :NEW.permissions IS NULL THEN
        :NEW.permissions := 'Full Access';
    END IF;
END;
/
ALTER TRIGGER "TRG_ADMIN_DEFAULT" ENABLE;

  ALTER TABLE "CART" ADD CONSTRAINT "FK_CART_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CART_CREATED_DATE" 
BEFORE INSERT ON CART
FOR EACH ROW
BEGIN
    IF :NEW.created_date IS NULL THEN
        :NEW.created_date := SYSTIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_CART_CREATED_DATE" ENABLE;

  ALTER TABLE "CART_ITEM" ADD CONSTRAINT "FK_CARTITEM_CART" FOREIGN KEY ("CART_ID")
	  REFERENCES "CART" ("CART_ID") ENABLE;
  ALTER TABLE "CART_ITEM" ADD CONSTRAINT "FK_CARTITEM_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CARTITEM_SET_PRICE" 
BEFORE INSERT ON CART_ITEM
FOR EACH ROW
DECLARE
    v_price PRODUCT.price%TYPE;
BEGIN
    SELECT price
    INTO v_price
    FROM PRODUCT
    WHERE product_id = :NEW.product_id;

    :NEW.price := v_price;
END;
/
ALTER TRIGGER "TRG_CARTITEM_SET_PRICE" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CARTITEM_VALIDATE" 
BEFORE INSERT ON CART_ITEM
FOR EACH ROW
BEGIN
    IF :NEW.quantity IS NULL OR :NEW.quantity <= 0 THEN
        RAISE_APPLICATION_ERROR(-20017, 'Quantity must be greater than 0');
    END IF;

    IF :NEW.price IS NULL OR :NEW.price <= 0 THEN
        RAISE_APPLICATION_ERROR(-20018, 'Price must be greater than 0');
    END IF;
END;
/
ALTER TRIGGER "TRG_CARTITEM_VALIDATE" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CATEGORY_VALIDATE_NAME" 
BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
    IF :NEW.category_name IS NULL THEN
        RAISE_APPLICATION_ERROR(-20007, 'Category name is required');
    END IF;
END;
/
ALTER TRIGGER "TRG_CATEGORY_VALIDATE_NAME" ENABLE;

  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "FK_CUSTOMER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM_USER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CUSTOMER_LOYALTY" 
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    IF :NEW.loyalty_points IS NULL THEN
        :NEW.loyalty_points := 0;
    END IF;
END;
/
ALTER TRIGGER "TRG_CUSTOMER_LOYALTY" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CUSTOMER_VALIDATE_USER" 
BEFORE INSERT ON CUSTOMER
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM SYSTEM_USER
    WHERE user_id = :NEW.user_id;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'User does not exist in SYSTEM_USER');
    END IF;
END;
/
ALTER TRIGGER "TRG_CUSTOMER_VALIDATE_USER" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_DISCOUNT_VALIDATE_DATES" 
BEFORE INSERT ON DISCOUNT
FOR EACH ROW
BEGIN
    IF :NEW.start_date IS NOT NULL AND :NEW.end_date IS NOT NULL THEN
        IF :NEW.end_date < :NEW.start_date THEN
            RAISE_APPLICATION_ERROR(-20027, 'End date cannot be before start date');
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_DISCOUNT_VALIDATE_DATES" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_DISCOUNT_VALIDATE_RATE" 
BEFORE INSERT ON DISCOUNT
FOR EACH ROW
BEGIN
    IF :NEW.discount_rate IS NULL OR :NEW.discount_rate < 0 OR :NEW.discount_rate > 100 THEN
        RAISE_APPLICATION_ERROR(-20026, 'Discount rate must be between 0 and 100');
    END IF;
END;
/
ALTER TRIGGER "TRG_DISCOUNT_VALIDATE_RATE" ENABLE;

  ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_ORDER_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("USER_ID") ENABLE;
  ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_ORDER_SLOT" FOREIGN KEY ("SLOT_ID")
	  REFERENCES "COLLECTION_SLOT" ("SLOT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_COLLECTION_TIME" 
BEFORE INSERT ON ORDERS
FOR EACH ROW
DECLARE
    v_collection_date DATE;
BEGIN
    SELECT collection_date INTO v_collection_date
    FROM COLLECTION_SLOT
    WHERE slot_id = :NEW.slot_id;

    IF v_collection_date < SYSDATE + 1 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Collection must be at least 24 hours later');
    END IF;
END;
/
ALTER TRIGGER "TRG_CHECK_COLLECTION_TIME" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_SLOT_CAPACITY" 
BEFORE INSERT ON ORDERS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ORDERS
    WHERE slot_id = :NEW.slot_id;

    IF v_count >= 20 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Slot is full');
    END IF;
END;
/
ALTER TRIGGER "TRG_CHECK_SLOT_CAPACITY" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ORDERS_DEFAULT_STATUS" 
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.status IS NULL THEN
        :NEW.status := 'Pending';
    END IF;
END;
/
ALTER TRIGGER "TRG_ORDERS_DEFAULT_STATUS" ENABLE;

  ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_ORDERITEM_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "ORDER_ITEM" ADD CONSTRAINT "FK_ORDERITEM_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_MIN_MAX_ORDER" 
BEFORE INSERT OR UPDATE ON ORDER_ITEM
FOR EACH ROW
DECLARE
    v_min NUMBER;
    v_max NUMBER;
BEGIN
    SELECT min_order, max_order INTO v_min, v_max
    FROM PRODUCT
    WHERE product_id = :NEW.product_id;

    IF :NEW.quantity < v_min OR :NEW.quantity > v_max THEN
        RAISE_APPLICATION_ERROR(-20002, 'Quantity outside allowed range');
    END IF;
END;
/
ALTER TRIGGER "TRG_CHECK_MIN_MAX_ORDER" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CHECK_STOCK" 
BEFORE INSERT OR UPDATE ON ORDER_ITEM
FOR EACH ROW
DECLARE
    v_stock NUMBER;
BEGIN
    SELECT stock_quantity INTO v_stock
    FROM PRODUCT
    WHERE product_id = :NEW.product_id;

    IF :NEW.quantity > v_stock THEN
        RAISE_APPLICATION_ERROR(-20001, 'Not enough stock available');
    END IF;
END;
/
ALTER TRIGGER "TRG_CHECK_STOCK" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_REDUCE_STOCK" 
AFTER INSERT ON ORDER_ITEM
FOR EACH ROW
BEGIN
    UPDATE PRODUCT
    SET stock_quantity = stock_quantity - :NEW.quantity
    WHERE product_id = :NEW.product_id;
END;
/
ALTER TRIGGER "TRG_REDUCE_STOCK" ENABLE;

  ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PAYMENT_METHOD" FOREIGN KEY ("METHOD_ID")
	  REFERENCES "PAYMENT_METHOD" ("METHOD_ID") ENABLE;
  ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PAYMENT_ORDER" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ORDERS" ("ORDER_ID") ENABLE;
  ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PAYMENT_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM_USER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PAYMENT_DEFAULT_STATUS" 
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    IF :NEW.payment_status IS NULL THEN
        :NEW.payment_status := 'Pending';
    END IF;
END;
/
ALTER TRIGGER "TRG_PAYMENT_DEFAULT_STATUS" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PAYMENT_SET_DATE" 
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    IF :NEW.payment_date IS NULL THEN
        :NEW.payment_date := SYSTIMESTAMP;
    END IF;
END;
/
ALTER TRIGGER "TRG_PAYMENT_SET_DATE" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PAYMENTMETHOD_VALIDATE" 
BEFORE INSERT ON PAYMENT_METHOD
FOR EACH ROW
BEGIN
    IF :NEW.method_name IS NULL THEN
        RAISE_APPLICATION_ERROR(-20022, 'Payment method name is required');
    END IF;
END;
/
ALTER TRIGGER "TRG_PAYMENTMETHOD_VALIDATE" ENABLE;

  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORY" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRODUCT_SHOP" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "SHOP" ("SHOP_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PRODUCT_BI" 
BEFORE INSERT ON product
FOR EACH ROW
BEGIN
  IF :NEW.product_id IS NULL THEN
    SELECT products_seq.NEXTVAL
    INTO :NEW.product_id
    FROM dual;
  END IF;
END;
/
ALTER TRIGGER "PRODUCT_BI" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRODUCT_ALLERGY" 
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    -- If allergy_info is empty, assign default
    IF :NEW.allergy_info IS NULL THEN
        :NEW.allergy_info := 'No known allergies';
    END IF;
END;
/
ALTER TRIGGER "TRG_PRODUCT_ALLERGY" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRODUCT_EXPIRY" 
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    IF :NEW.expiry_date IS NOT NULL AND :NEW.expiry_date < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20016, 'Expiry date cannot be in the past');
    END IF;
END;
/
ALTER TRIGGER "TRG_PRODUCT_EXPIRY" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRODUCT_VALIDATE" 
BEFORE INSERT ON PRODUCT
FOR EACH ROW
BEGIN
    IF :NEW.product_name IS NULL THEN
        RAISE_APPLICATION_ERROR(-20012, 'Product name is required');
    END IF;

    IF :NEW.price IS NULL OR :NEW.price <= 0 THEN
        RAISE_APPLICATION_ERROR(-20013, 'Price must be greater than 0');
    END IF;

    IF :NEW.stock_quantity IS NULL OR :NEW.stock_quantity < 0 THEN
        RAISE_APPLICATION_ERROR(-20014, 'Stock quantity cannot be negative');
    END IF;

    IF :NEW.min_order IS NOT NULL AND :NEW.max_order IS NOT NULL THEN
        IF :NEW.min_order > :NEW.max_order THEN
            RAISE_APPLICATION_ERROR(-20015, 'Minimum order cannot be greater than maximum order');
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_PRODUCT_VALIDATE" ENABLE;

  ALTER TABLE "PRODUCT_DISCOUNT" ADD CONSTRAINT "FK_PRODUCTDISCOUNT_DISCOUNT" FOREIGN KEY ("DISCOUNT_ID")
	  REFERENCES "DISCOUNT" ("DISCOUNT_ID") ENABLE;
  ALTER TABLE "PRODUCT_DISCOUNT" ADD CONSTRAINT "FK_PRODUCTDISCOUNT_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRODUCTDISCOUNT_UNIQUE" 
BEFORE INSERT ON PRODUCT_DISCOUNT
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM PRODUCT_DISCOUNT
    WHERE product_id = :NEW.product_id
      AND discount_id = :NEW.discount_id;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20028, 'This product already has this discount');
    END IF;
END;
/
ALTER TRIGGER "TRG_PRODUCTDISCOUNT_UNIQUE" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PRODUCTDISCOUNT_VALIDATE_DATE" 
BEFORE INSERT ON PRODUCT_DISCOUNT
FOR EACH ROW
DECLARE
    v_start DATE;
    v_end DATE;
BEGIN
    SELECT start_date, end_date
    INTO v_start, v_end
    FROM DISCOUNT
    WHERE discount_id = :NEW.discount_id;

    IF v_start IS NOT NULL AND v_end IS NOT NULL THEN
        IF SYSDATE < v_start OR SYSDATE > v_end THEN
            RAISE_APPLICATION_ERROR(-20029, 'Discount is not active');
        END IF;
    END IF;
END;
/
ALTER TRIGGER "TRG_PRODUCTDISCOUNT_VALIDATE_DATE" ENABLE;

  ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_REVIEW_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "CUSTOMER" ("USER_ID") ENABLE;
  ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_REVIEW_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PRODUCT" ("PRODUCT_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_REVIEW_VALIDATE_RATING" 
BEFORE INSERT ON REVIEW
FOR EACH ROW
BEGIN
    IF :NEW.rating IS NULL OR :NEW.rating < 1 OR :NEW.rating > 5 THEN
        RAISE_APPLICATION_ERROR(-20025, 'Rating must be between 1 and 5');
    END IF;
END;
/
ALTER TRIGGER "TRG_REVIEW_VALIDATE_RATING" ENABLE;

  ALTER TABLE "SHOP" ADD CONSTRAINT "FK_SHOP_TRADER" FOREIGN KEY ("TRADER_ID")
	  REFERENCES "TRADER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_SHOP_UNIQUE_NAME" 
BEFORE INSERT ON SHOP
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM SHOP
    WHERE LOWER(shop_name) = LOWER(:NEW.shop_name);

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Shop name already exists');
    END IF;
END;
/
ALTER TRIGGER "TRG_SHOP_UNIQUE_NAME" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_SYSTEM_USER_ID" 
BEFORE INSERT ON SYSTEM_USER
FOR EACH ROW
BEGIN
    IF :NEW.user_id IS NULL THEN
        SELECT seq_system_user.NEXTVAL
        INTO :NEW.user_id
        FROM dual;
    END IF;
END;
/
ALTER TRIGGER "TRG_SYSTEM_USER_ID" ENABLE;

  ALTER TABLE "TRADER" ADD CONSTRAINT "FK_TRADER_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYSTEM_USER" ("USER_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_TRADER_LICENSE_CHECK" 
BEFORE INSERT ON TRADER
FOR EACH ROW
BEGIN
    IF :NEW.license_no IS NULL THEN
        RAISE_APPLICATION_ERROR(-20005, 'License number is required');
    END IF;
END;
/
ALTER TRIGGER "TRG_TRADER_LICENSE_CHECK" ENABLE;
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_TRADER_VALIDATE_BUSINESS" 
BEFORE INSERT ON TRADER
FOR EACH ROW
BEGIN
    IF :NEW.business_name IS NULL THEN
        RAISE_APPLICATION_ERROR(-20006, 'Business name is required');
    END IF;
END;
/
ALTER TRIGGER "TRG_TRADER_VALIDATE_BUSINESS" ENABLE;