UPDATE ORDERS o
SET o.STATUS = 'Paid'
WHERE EXISTS (
    SELECT 1
    FROM PAYMENT p
    WHERE p.ORDER_ID = o.ORDER_ID
      AND UPPER(p.PAYMENT_STATUS) = 'PAID'
)
AND (o.STATUS IS NULL OR UPPER(o.STATUS) = 'PENDING');

COMMIT;

