-- Drop the temporary ADMIN cleanup backup permanently.

SET SERVEROUTPUT ON

DECLARE
    v_backup_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_backup_exists
      FROM USER_TABLES
     WHERE TABLE_NAME = 'ADMIN_BACKUP_BEFORE_CLEANUP';

    IF v_backup_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE ADMIN_BACKUP_BEFORE_CLEANUP PURGE';
        DBMS_OUTPUT.PUT_LINE('Dropped ADMIN_BACKUP_BEFORE_CLEANUP permanently.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ADMIN_BACKUP_BEFORE_CLEANUP does not exist.');
    END IF;
END;
/

SELECT COUNT(*) AS BACKUP_TABLE_EXISTS
  FROM USER_TABLES
 WHERE TABLE_NAME = 'ADMIN_BACKUP_BEFORE_CLEANUP';
