-- Guard ADMIN and CART against accidental generator/import pollution.

SET SERVEROUTPUT ON

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM CART
     WHERE CUSTOMER_ID IS NULL;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20050, 'Cannot harden CART: NULL CUSTOMER_ID rows still exist.');
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM CART
     WHERE STATUS IS NULL
        OR STATUS NOT IN ('Active', 'Closed');

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20051, 'Cannot harden CART: invalid STATUS rows still exist.');
    END IF;

    SELECT COUNT(*)
      INTO v_count
      FROM CART
     WHERE CART_ID < 1
        OR CART_ID > 999999999;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20052, 'Cannot harden CART: out-of-range CART_ID rows still exist.');
    END IF;
END;
/

ALTER TABLE CART MODIFY (
    CUSTOMER_ID NOT NULL,
    STATUS NOT NULL,
    CREATED_DATE NOT NULL
);

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'CART'
       AND CONSTRAINT_NAME = 'CHK_CART_STATUS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE CART ADD CONSTRAINT CHK_CART_STATUS
            CHECK (STATUS IN ('Active', 'Closed'))
        ]';
        DBMS_OUTPUT.PUT_LINE('Added CHK_CART_STATUS.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CHK_CART_STATUS already exists.');
    END IF;

    SELECT COUNT(*)
      INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'CART'
       AND CONSTRAINT_NAME = 'CHK_CART_ID_RANGE';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE CART ADD CONSTRAINT CHK_CART_ID_RANGE
            CHECK (CART_ID BETWEEN 1 AND 999999999)
        ]';
        DBMS_OUTPUT.PUT_LINE('Added CHK_CART_ID_RANGE.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('CHK_CART_ID_RANGE already exists.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CART_CREATED_DATE
BEFORE INSERT OR UPDATE OF CREATED_DATE ON CART
FOR EACH ROW
BEGIN
    IF :NEW.CREATED_DATE IS NULL THEN
        :NEW.CREATED_DATE := SYSTIMESTAMP;
    END IF;

    IF :NEW.CREATED_DATE > SYSTIMESTAMP + INTERVAL '5' MINUTE THEN
        RAISE_APPLICATION_ERROR(-20053, 'CART.CREATED_DATE cannot be in the future.');
    END IF;

    IF :NEW.CREATED_DATE < TIMESTAMP '2020-01-01 00:00:00' THEN
        RAISE_APPLICATION_ERROR(-20054, 'CART.CREATED_DATE is unrealistically old.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADMIN_DEFAULT
BEFORE INSERT OR UPDATE ON ADMIN
FOR EACH ROW
DECLARE
    v_email SYSTEM_USER.EMAIL%TYPE;
BEGIN
    IF :NEW.ADMIN_ROLE IS NULL THEN
        :NEW.ADMIN_ROLE := 'Manager';
    END IF;

    IF :NEW.PERMISSIONS IS NULL THEN
        :NEW.PERMISSIONS := 'Full Access';
    END IF;

    SELECT EMAIL
      INTO v_email
      FROM SYSTEM_USER
     WHERE USER_ID = :NEW.USER_ID;

    IF LOWER(v_email) <> 'admin@test.com' THEN
        RAISE_APPLICATION_ERROR(-20055, 'Only admin@test.com may be stored in ADMIN.');
    END IF;
END;
/

COMMIT;

PROMPT ADMIN/CART hardening check:
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS
  FROM USER_CONSTRAINTS
 WHERE (TABLE_NAME = 'CART' AND CONSTRAINT_NAME IN ('CHK_CART_STATUS', 'CHK_CART_ID_RANGE'))
    OR (TABLE_NAME = 'CART' AND CONSTRAINT_TYPE = 'R')
    OR (TABLE_NAME = 'ADMIN' AND CONSTRAINT_TYPE = 'R')
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;

SELECT TRIGGER_NAME, TABLE_NAME, STATUS
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME IN ('TRG_CART_CREATED_DATE', 'TRG_ADMIN_DEFAULT')
 ORDER BY TRIGGER_NAME;
