<?php
/**
 * Register Page - Cleckhuddesfax Online Mart
 * 
 * This page handles:
 * 1. SHOW the registration form (when user visits the page)
 * 2. PROCESS the form (when user clicks Register)
 *    - Inserts a new row into SYSTEM_USER table
 *    - Inserts a new row into CUSTOMER table (if customer role)
 */

// -------------------------------------------------------
// Start Session so we can log the user in right after registering
// -------------------------------------------------------
session_start();

// If already logged in, redirect to profile
if (isset($_SESSION['user_id'])) {
    header("Location: profile.php");
    exit();
}

// Connect to Oracle database
include 'db.php';

$error_message   = "";
$success_message = "";

// -------------------------------------------------------
// CHECK IF THE REGISTRATION FORM WAS SUBMITTED
// -------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // -------------------------------------------------------
    // STEP 1: Get all the data the user typed in the form
    // -------------------------------------------------------
    $name     = trim($_POST['name']);
    $email    = trim($_POST['email']);
    $password = trim($_POST['password']);
    $address  = trim($_POST['address']);
    $role     = trim($_POST['role']); // "customer" or "trader"

    // -------------------------------------------------------
    // STEP 2: Validate — make sure no fields are empty
    // -------------------------------------------------------
    if (empty($name) || empty($email) || empty($password) || empty($address)) {
        $error_message = "All fields are required. Please fill in the form completely.";

    } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        // Check if the email format is valid (e.g. must have @ and .)
        $error_message = "Please enter a valid email address.";

    } elseif (strlen($password) < 6) {
        // Password must be at least 6 characters long
        $error_message = "Password must be at least 6 characters long.";

    } else {
        // -------------------------------------------------------
        // STEP 3: Check if the email is already registered
        // We cannot have two users with the same email (UNIQUE constraint)
        // -------------------------------------------------------
        $check_sql  = "SELECT COUNT(*) AS CNT FROM SYSTEM_USER WHERE UPPER(TRIM(EMAIL)) = UPPER(TRIM(:email))";
        $check_stmt = oci_parse($conn, $check_sql);
        oci_bind_by_name($check_stmt, ':email', $email);
        oci_execute($check_stmt);
        $check_row = oci_fetch_array($check_stmt, OCI_ASSOC);
        oci_free_statement($check_stmt);

        if ($check_row['CNT'] > 0) {
            // Email already exists in the database
            $error_message = "That email address is already registered. Please login instead.";

        } else {
            // -------------------------------------------------------
            // STEP 4: Insert the new user into SYSTEM_USER table
            // The USER_ID is automatically generated by the database
            // trigger (TRG_SYSTEM_USER_ID uses seq_system_user.NEXTVAL)
            // -------------------------------------------------------
            $insert_user_sql = "INSERT INTO SYSTEM_USER (NAME, EMAIL, PASSWORD, ADDRESS, STATUS, CREATED_AT)
                                VALUES (:name, :email, :password, :address, 'Active', SYSDATE)";

            $insert_stmt = oci_parse($conn, $insert_user_sql);

            // Bind each form value to its placeholder in the SQL
            oci_bind_by_name($insert_stmt, ':name',     $name);
            oci_bind_by_name($insert_stmt, ':email',    $email);
            oci_bind_by_name($insert_stmt, ':password', $password);
            oci_bind_by_name($insert_stmt, ':address',  $address);

            // Execute the INSERT
            $insert_success = oci_execute($insert_stmt);
            oci_free_statement($insert_stmt);

            if (!$insert_success) {
                // Something went wrong with the INSERT
                $err = oci_error($conn);
                $error_message = "Registration failed. Please try again.";
            } else {
                // -------------------------------------------------------
                // STEP 5: Get the new USER_ID that was just created
                // We need it to insert into the CUSTOMER table next
                // -------------------------------------------------------
                $get_id_sql  = "SELECT USER_ID FROM SYSTEM_USER WHERE UPPER(TRIM(EMAIL)) = UPPER(TRIM(:email))";
                $get_id_stmt = oci_parse($conn, $get_id_sql);
                oci_bind_by_name($get_id_stmt, ':email', $email);
                oci_execute($get_id_stmt);
                $new_user = oci_fetch_array($get_id_stmt, OCI_ASSOC);
                oci_free_statement($get_id_stmt);

                $new_user_id = $new_user['USER_ID'];

                // -------------------------------------------------------
                // STEP 6: Insert into the CUSTOMER or TRADER table
                // The CUSTOMER table is linked to SYSTEM_USER by USER_ID
                // LOYALTY_POINTS defaults to 0 (handled by DB trigger)
                // -------------------------------------------------------
                if ($role === 'customer') {
                    $role_sql  = "INSERT INTO CUSTOMER (USER_ID) VALUES (:uid)";
                    $role_stmt = oci_parse($conn, $role_sql);
                    oci_bind_by_name($role_stmt, ':uid', $new_user_id);
                    oci_execute($role_stmt);
                    oci_free_statement($role_stmt);
                }
                // Note: Trader registration needs a Business Name and License No.
                // Those fields are not in the current register form.
                // If the role is "trader", you may want to add those fields.

                // -------------------------------------------------------
                // STEP 7: Registration complete! 
                // Log the user in automatically by setting session variables
                // -------------------------------------------------------
                $_SESSION['user_id']    = $new_user_id;
                $_SESSION['user_name']  = $name;
                $_SESSION['user_email'] = $email;
                $_SESSION['user_role']  = $role;

                // Send the user to their profile page
                header("Location: profile.php");
                exit();
            }
        }
    }

    oci_close($conn);
}

// Show the page
include 'header.php';
?>

<!-- Register Section -->
<section class="auth-page">
    <div class="auth-card">
        <h1>REGISTRATION</h1>
        <div class="auth-subtitle">Create your account to get started</div>

        <?php
        // Show error message if there is one
        if (!empty($error_message)) {
            echo '<div class="auth-error">' . htmlspecialchars($error_message) . '</div>';
        }
        ?>

        <div class="auth-tabs">
            <div class="auth-tab active" id="tab-customer">CUSTOMER</div>
            <div class="auth-tab" id="tab-trader">TRADER</div>
        </div>

        <!-- The form submits to register.php (this same page) -->
        <form action="register.php" method="POST" id="register-form">
            <!-- Hidden field updated by JavaScript when tab is clicked -->
            <input type="hidden" name="role" id="role-input" value="customer">

            <div class="auth-form-group">
                <div class="auth-label">FULL NAME</div>
                <!-- name="name" matches $_POST['name'] in the PHP above -->
                <input type="text" class="auth-input" name="name" required
                       value="<?php echo isset($_POST['name']) ? htmlspecialchars($_POST['name']) : ''; ?>">
            </div>

            <div class="auth-form-group">
                <div class="auth-label">EMAIL ADDRESS</div>
                <input type="email" class="auth-input" name="email" required
                       value="<?php echo isset($_POST['email']) ? htmlspecialchars($_POST['email']) : ''; ?>">
            </div>

            <div class="auth-form-group">
                <div class="auth-label">PASSWORD</div>
                <input type="password" class="auth-input" name="password" required>
            </div>

            <div class="auth-form-group">
                <div class="auth-label">HOME ADDRESS</div>
                <textarea class="auth-input" name="address" required><?php echo isset($_POST['address']) ? htmlspecialchars($_POST['address']) : ''; ?></textarea>
            </div>

            <button type="submit" class="btn-auth" id="register-btn">REGISTER</button>
        </form>
    </div>

    <div class="auth-footer">
        <span class="auth-footer-text">ALREADY HAVE AN ACCOUNT?</span>
        <a href="login.php" class="auth-footer-link">LOGIN</a>
    </div>
</section>

<?php include 'footer.php'; ?>